trigger: 
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '12.x'
      displayName: 'install node.js'

    - script: |
          npm install
      displayName: 'npm install --no-package-lock'

    - script: |
          npm run test
      displayName: 'npm run test'

    - script: |
          npm run lint
      displayName: 'npm run lint'

    - script: |
          npm run docs
      displayName: 'npm run docs'

    - script: |
          echo '//registry.npmjs.org/:_authToken=$(token)' > .npmrc
      displayName: 'npmrc token'
      condition: and(succeeded(), or(eq(variables['force.push'], true), eq(variables['build.sourceBranch'], 'refs/heads/master')))


    - script: |
          git update-index --assume-unchanged .npmrc
      displayName: 'git index'
      condition: and(succeeded(), or(eq(variables['force.push'], true), eq(variables['build.sourceBranch'], 'refs/heads/master')))

    - script: |
          npm run publish
      displayName: 'npm run publish'
      condition: and(succeeded(), or(eq(variables['force.push'], true), eq(variables['build.sourceBranch'], 'refs/heads/master')))

    - task: Docker@2
      inputs:
        containerRegistry: 'Doctorlink Platform DVLP new'
        repository: 'doctorlink/npm'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
      condition: and(succeeded(), or(eq(variables['force.push'], true), eq(variables['build.sourceBranch'], 'refs/heads/master')))