trigger: none

pr:
  branches:
    include:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '12.x'
      displayName: 'install node.js'

    - script: |
          npm install
      displayName: 'npm install'

    - script: |
          npm run test
      displayName: 'npm run test'

    - script: |
          npm run build
      displayName: 'npm run build'

    - script: |
          npm run lint
      displayName: 'npm run lint'