# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
          npm install --global np
      displayName: 'Install NP'

    - checkout: self
      persistCredentials: true
      clean: true

    - script: |
          echo '//registry.npmjs.org/:_authToken=$(token)' > .npmrc
      displayName: 'Add token to npmrc'

    - script: |
          git config --global user.name "azdo"
          git config --global user.email "azdo@doctorlink.com"
          git switch master
      displayName: 'Git Master'

    - script: |
          np $(version) --tag $(tag) --yolo
      displayName: 'Run np'